Repository meshery/meshery-operator, pull requests merged in 2022-09, with the labels that each got.

#368 add repo to image name
  Makefile
Labels: area/ci, area/devops

#369 Use DeepCopy instead of passing by reference
  pkg/broker/broker.go
  pkg/meshsync/meshsync.go
Labels: component/meshsync

#376 Perform correct cleanup using ownerReferences
  controllers/broker_controller.go
  controllers/meshsync_controller.go
  main.go
  pkg/broker/resources.go
Labels: area/lifecycle
