Repository meshery/meshery-operator, pull requests merged in 2023-05, with the labels that each got.

#461 Increase the test coverage from 20% to 49%
  Makefile
  api/v1alpha1/broker_types_test.go
  api/v1alpha1/meshsync_types_test.go
Labels: area/tests, language/go

#468 Include CodeCov
  .github/workflows/ci.yml
Labels: area/ci, area/tests, language/go

#471 Replace CI jobs, make sure the checking and coverage is reasonable
  .github/workflows/approve-to-run-ci.yml
  .github/workflows/ci.yml
Labels: area/ci

#473 Add suitest for controller
  .github/workflows/approve-to-run-ci.yml
  Makefile
  controllers/broker_controller_test.go
  controllers/error.go
  controllers/suit_test.go
  go.mod
  go.sum
Labels: area/tests, language/go

#481 Feat/reconcile coverage
  controllers/error.go
  controllers/meshsync_controller_test.go
  controllers/suit_test.go
Labels: area/tests, language/go

#477 Update approve-to-run-ci.yml
  .github/workflows/approve-to-run-ci.yml
Labels: area/ci
